# Generated by Django 4.2.6 on 2023-10-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_categoria",
                    models.CharField(max_length=100, verbose_name="nombre Categoria"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaCreacion", models.DateField(verbose_name="fecha Creacion")),
                (
                    "fechaActualizacion",
                    models.DateField(verbose_name="fecha Actualizacion"),
                ),
                ("imagen", models.ImageField(upload_to="", verbose_name="imagen")),
                ("numero_horas", models.IntegerField(verbose_name="numeroHoras")),
            ],
        ),
        migrations.CreateModel(
            name="Interes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ManyToManyField(
                        related_name="categorias", to="tiempo.categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=50, verbose_name="nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=50, verbose_name="apellidos"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("h", "Hombre"), ("m", "Mujer")],
                        max_length=1,
                        verbose_name="genero",
                    ),
                ),
                (
                    "documento_identificacion",
                    models.CharField(max_length=50, verbose_name="cedula"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="email")),
                ("telefono", models.CharField(max_length=50, verbose_name="telefono")),
                ("fechaNacimiento", models.DateField(verbose_name="fecha Nacimiento")),
                (
                    "direccion",
                    models.CharField(max_length=150, verbose_name="direccion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_rol",
                    models.CharField(
                        choices=[("1", "Administrador"), ("2", "Cliente")],
                        max_length=50,
                        verbose_name="nombreRol",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Categorias",
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tiempo.persona",
                    ),
                ),
                (
                    "nombre_usuario",
                    models.CharField(max_length=50, verbose_name="usuario"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="password")),
                (
                    "rol",
                    models.ManyToManyField(related_name="usuarios", to="tiempo.rol"),
                ),
            ],
            bases=("tiempo.persona",),
        ),
        migrations.AddField(
            model_name="interes",
            name="usuarioIntereses",
            field=models.ManyToManyField(related_name="intereses", to="tiempo.usuario"),
        ),
        migrations.AddField(
            model_name="cuenta",
            name="usuarioCuenta",
            field=models.ManyToManyField(related_name="cuentas", to="tiempo.usuario"),
        ),
    ]
