# Generated by Django 4.2.6 on 2023-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="usuarios", to="tiempo.rol"
            ),
        ),
    ]
