# Generated by Django 4.2.6 on 2023-10-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0002_alter_persona_direccion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transacciontiempo",
            name="ofertante",
        ),
        migrations.AddField(
            model_name="transacciontiempo",
            name="servicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tiempo.servicio",
            ),
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="propietario",
        ),
        migrations.AddField(
            model_name="servicio",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tiempo.usuario",
            ),
        ),
    ]
