# Generated by Django 4.2.6 on 2023-10-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0002_categoria_cuenta_interes_persona_rol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rol",
            name="nombre_rol",
            field=models.CharField(
                choices=[("administrador", "Administrador"), ("cliente", "Cliente")],
                max_length=50,
                verbose_name="nombreRol",
            ),
        ),
        migrations.CreateModel(
            name="Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Titulo")),
                (
                    "descripcion_actividad",
                    models.CharField(max_length=256, verbose_name="descripcion"),
                ),
                (
                    "tiempo_requerido",
                    models.IntegerField(verbose_name="numero de horas requerida"),
                ),
                ("fecha_creacion", models.DateField(verbose_name="fecha_creacion")),
                ("fecha_vigente", models.DateField(verbose_name="fecha_vigente")),
                (
                    "propietario",
                    models.ManyToManyField(
                        related_name="propietario", to="tiempo.usuario"
                    ),
                ),
            ],
        ),
    ]
