# Generated by Django 4.2.6 on 2023-10-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0002_remove_categoria_nombre_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="calificacion",
            name="calificacionServicio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificacionServicio",
                to="tiempo.transacciontiempo",
            ),
        ),
        migrations.AddField(
            model_name="transacciontiempo",
            name="servicioTransaccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicioTransaccion",
                to="tiempo.servicio",
            ),
        ),
    ]
